var colors = require('cli-color')
var watchify = require('watchify')
var catw = require('catw')
var mcss = require('micro-css')
var Concat = require('concat-stream')
var watchViews = require('rincewind-watch')
var gaze = require('gaze')
var getResourceKey = require('unique-resource')
var notify = require('growl')

var fs = require('fs')
process.cwd(__dirname)
if (!fs.existsSync('build')){
  fs.mkdirSync('build')
}

var pendingSteps = 0
function pendingStep(){
  pendingSteps += 1
}
function popStep(){
  pendingSteps -= 1
  if (!pendingSteps){
    if (~process.argv.indexOf('-w') || ~process.argv.indexOf('--watch')){
      console.log('Build complete. Watching for changes...')
    } else {
      process.exit()
    }
  }
}

var viewPath = __dirname + '/views'

// index.html
pendingStep()
watchViews({
  window: viewPath + '/window.html'
}, function(views, changedFiles){
  fs.writeFileSync(viewPath + '/index.js', getViewsModule(views, viewPath))
  changedFiles.forEach(function(f){
    if (/.js$/.exec(f) && require.cache[f]){
      ;delete require.cache[f]
    }
  })
  fs.writeFile('build/index.html', views.window(), popStep)
})

function getViewsModule(views, relativeTo){
  var results = Object.keys(views).map(function(key){
    return key + ': View(' + views[key].stringify(relativeTo) + ')' 
  })
  return '// generated by ../build.js\n' + 
    'var View = require("rincewind")\n' + 
    'module.exports = {\n  ' + results.join(',\n  ') + '\n}'
}

// manifest.json / background.js
pendingStep()
pendingStep()
catw('package.json', function(stream){
  stream.pipe(Concat(function(data){
    var pkg = JSON.parse(data)
    fs.writeFile('build/manifest.json', JSON.stringify({
      name: 'Loop Drop',
      version: pkg.version,
      description: pkg.description,
      author: pkg.author,
      manifest_version: 2,
      permissions: pkg.permissions,
      app: {
        background: {
          scripts: ['background.js']
        }
      }//,
      //icons: {
      //  16: "icon-16.png", 
      //  128: "icon-128.png"
      //}
    }, null, 2), popStep)

    fs.writeFile(
      'build/background.js', 
      "chrome.app.runtime.onLaunched.addListener(function() { \n" +
      "  chrome.app.window.create('index.html', " + JSON.stringify(pkg.window || null) + ")\n" +
      "})", popStep
    )

  }))
})

// resource.css
pendingStep()
gaze('**/*.mcss', function(err, watcher){

  var styles = {}
  var cache = {}

  function update(filepath){
    var key = getResourceKey(filepath, {cache: false})
    var content = fs.readFileSync(filepath)
    content = mcss(key + ' { ' + content + ' }')

    if (content){
      styles[filepath] = content
    } else {
      delete styles[filepath]
    }

  }

  function dumpFile(){
    var content = ''
    Object.keys(styles).forEach(function(k){
      content += styles[k]
    })
    fs.writeFile('build/resource.css', content, popStep)
  }

  this.watched(function(err, watched) {
    for (var dir in watched){
      for (var i=0;i<watched[dir].length;i++){
        var file = watched[dir][i]
        if (file.slice(-5) === '.mcss'){
          update(file)
        }
      }
    }
    dumpFile()
  })

  this.on('changed', function(filepath){
    update(filepath)
    dumpFile()
  })
})

// bundle.css
pendingStep()
catw('styles/*.mcss', function(stream){
  stream.pipe(Concat(function(data){
    fs.writeFile('build/bundle.css', mcss(String(data)), popStep)
  }))
})

// extra.css
pendingStep()
catw('styles/*.css', function(stream){
  stream.pipe(fs.createWriteStream('build/extra.css')).on('finish', popStep)
})

// bundle.js
pendingStep()
var w = watchify('./index.js')
var pendingBundleError = false
w.on('update', bundle)
bundle()
function bundle(){
  w.bundle({debug: true}).on('error', handleError).pipe(fs.createWriteStream('build/bundle.js')).on('finish', function(){
    popStep()
    handleSucess()
  })
}

function handleSucess(){
  if (pendingBundleError){
    pendingBundleError = false
    console.log('** ' + colors.green('Rebuild successful!') + ' **')
    notify('Rebuild Succeeded', {title: 'Loop Drop'})
  }
}

function handleError(err){
  console.log('** ' + colors.red('REBUILD ERROR') + ' **')
  var message = (err&&err.message||err||'Error').replace(/([\/][^\/ ]+)+(([\/][^\/ ]+){2}( |$))/g, ".$2")
    .replace(/: Line ([0-9]+)/, ":$1")
  console.error(message)
  notify(message, {title: 'Loop Drop', image: 'js'})
  pendingBundleError = true
}