echo "Signing Bundle..."
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Electron Helper.app"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Mantle.framework"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Electron Framework"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Electron Framework.framework"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Electron Helper NP.app"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/ReactiveCocoa.framework"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Electron Helper EH.app"
codesign -s 989QCZP56K -f "build/Loop Drop.app/Contents/Frameworks/Squirrel.framework"
codesign -s 989QCZP56K -f "build/Loop Drop.app"